name: 新功能提案
description: 为启动器提供一些新点子
labels: ["新功能提案"]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "我确认在Issues列表中并无其他人已经建议过相似的功能"
    - label: "我已认真阅读《ACLissue库提交新标签规范》，并愿意遵守其中的规则"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 这个新功能是可以解决目前存在的某个问题或BUG吗？
    placeholder: "-（请在这里回答）-"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 期望的功能描述
    placeholder: "-（请在这里回答）-"
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: 备注
    placeholder: "-（请在这里回答）-"
